### ISSUE TITLE
make sure that the generated shortid is not the  same as an existing session

### ISSUE THREAD

**Issue by girishso** [girishso/elm-repl-in-browser#3]
## Posting on behalf of Noah Hall (@eeue56) from elm-dev

On this line -> 
https://github.com/girishso/elm-repl-in-browser/blob/master/src/app.js#L23 

You probably wanna make sure that the generated shortid is not the 
same as an existing session with logs - that would remove any concern 
to the users and fix both 1 and 2 :)

**Comment by girishso** [comment]
I thought shortids are unique, if not I will rather use guids to not have to deal with clashing ids.

**Comment by eeue56** [comment]
They're definitely not unique, but they are very random over a wide distribution. It's likely only a problem you'll face if someone is really out to get you :)

**Comment by girishso** [comment]
:)

With rate limits in place I don't think I will run into that situation!
