### ISSUE TITLE
http://elmrepl.cuberoot.in/ is done

### ISSUE THREAD

**Issue by sebsheep** [girishso/elm-repl-in-browser#4]
Hello,

The web interface seems down : http://elmrepl.cuberoot.in/ .

(Error displayed : 502 Bad Gateway)

Can you repair ?

**Comment by girishso** [comment]
It's up and running now.

**Comment by girishso** [comment]
Thanks for letting me know!

**Comment by sebsheep** [comment]
You are welcome.

Do you know how stable will be this site? I would like to use it for a
workshop in June, will it be up at this time?

Moreover, the website runs elm0.19 REPL but the repo seems to be with 0.18
only. Is the repo up to date?



Le mer. 15 mai 2019 à 07:50, Girish Sonawane <notifications@github.com> a
écrit :

**Comment by girishso** [comment]
Yes the repo is not updated to 0.19, will fix that.

The server is pretty stable, the hosting company restarted the server and the repl server was not booted, that’s why the error.

You can notify me in June, around the workshop day and I’ll make sure everything is alright.  

Btw. the server  has a 20 minutes inactivity timeout in case you didn’t notice.
